language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
services:
  - docker
env:
  global:
    - DB_NAME=transform
    - DB_USER=transform
    - DB_PASSWORD=bZVWia5P4fMwACDjUHDI
    - DB_HOST=localhost
    - DB_PORT=5433
    - CELERY_BROKER_URL=
    - DJANGO_LOGS_DIR=/tmp
cache:
  pip: true
before_script:
  - sudo make install
  - cd ../../
  - sudo apt-get install python-dev
before_install:
  - docker pull postgres:12
  - docker run -d -p 127.0.0.1:5433:5432 
    -e POSTGRES_DB=$DB_NAME 
    -e POSTGRES_USER=$DB_USER 
    -e POSTGRES_PASSWORD=$DB_PASSWORD 
    postgres:12
install:
  - pip install -r requirements.txt
script:
  - mkdir /tmp/media
  - mkdir /tmp/logs
  - mkdir static
  - cd src && ./manage.py test