# Generated by Django 2.1.2 on 2018-10-29 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pipelineresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineResultFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=666)),
                ('md5_hash', models.CharField(editable=False, max_length=64)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('pipeline_result', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='projects.PipelineResult')),
            ],
        ),
    ]
