# Generated by Django 2.1.2 on 2018-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_pipelineresultfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineresultfile",
            name="mimetype",
            field=models.CharField(blank=True, max_length=666, null=True),
        ),
    ]
