# Generated by Django 4.0.1 on 2022-01-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_pipelineresultfile_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='processors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineresult',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineresult',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='processor',
            name='ui_schema',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
